@startuml
!include include/iterator.puml
!include include/queue.puml
!include include/.list-randomaccess.puml
package java.util {
  
  class PriorityQueue<E> extends AbstractQueue {
    Priority Heap
  }
  class ArrayDeque<E> extends AbstractCollection implements Deque
  
  interface ListIterator<E> extends Iterator
  ListIterator <.d. List: creates
  
  abstract AbstractList<E> extends AbstractCollection implements List
  AbstractList .r.> RandomAccess: relates to
    ' Somehow `r` works but `l` doesn’t
  class ArrayList<E> extends AbstractList implements RandomAccess
  abstract AbstractSequentialList<E> extends AbstractList
  class LinkedList<E> extends AbstractSequentialList implements Deque
  
}
@enduml
