@startuml
!include include/iterator.puml
package java {
  
  package lang {
    interface Comparable<T>
  }
  package util {
    interface Comparator<T>
    Comparator .u. Comparable: alternatives
    interface Enumeration<E> <<obsolete>>
    Enumeration .u.> java.lang.Iterable: superseded by
    
    interface Spliterator<T>
    Spliterator <.r. Collection: creates
    metaclass Spliterators
    Spliterators <.d. Spliterator: utilities
    
    interface Map<K,V>
    metaclass Collections
    Collections <.d. Collection: utilities
    Collections <.d. Map: utilities
    
    interface SortedMap<K,V> extends Map
    SortedMap .u.> Comparator: depends on
    interface SortedSet<E> extends SequencedCollection
    SortedSet .u.> Comparator: depends on
    
    metaclass Arrays
    
  }
}
@enduml
