@startuml
!include include/iterator.puml
package java {
  
  package lang {
    interface Comparable<T>
  }
  package util {
    interface Comparator<T>
    Comparator .u. Comparable: alternatives
    
    interface Spliterator<T>
    Spliterator <.l. Collection: creates
    metaclass Spliterators
    Spliterators <.d. Spliterator: utilities
    
    interface Map<K,V>
    metaclass Collections
    Collections <.d. Collection: utilities
    Collections <.d. Map: utilities
    
    interface SortedMap<K,V> extends Map
    SortedMap -l-> Comparator
    interface SortedSet<E> extends Collection
    SortedSet -u-> Comparator
    
    'metaclass Arrays
    
  }
}
@enduml
