@startuml
!include include.puml
package java {
  
  package lang {
    interface Iterable<T>
    interface Comparable<T>
  }
  package util {
    interface Comparator<T>
    Comparator .u. Comparable
    
    interface Enumeration<E> <<obsolete>>
    Enumeration .u.> java.lang.Iterable
    interface Iterator<E>
    Iterator <.u. Iterable 
    
    interface Spliterator<T>
    Spliterator <.l. Collection 
    metaclass Spliterators
    Spliterators <.u. Spliterator
    
    interface Collection extends java.lang.Iterable
    
    interface Map<K,V>
    metaclass Collections
    Collections <.d. Collection
    Collections <.d. Map
    
    interface SortedMap<K,V> extends Map
    SortedMap .u.> Comparator
    interface SortedSet<E> extends SequencedCollection
    SortedSet .u.> Comparator
    
    metaclass Arrays
    
  }
}
@enduml
