@startuml
package java.util {
  
  interface Collection<E> ##blue
  abstract AbstractCollection<E> ##blue implements Collection
  interface SequencedCollection<E> <<New!>> ##blue extends Collection
  
}
@enduml
