@startuml
!include collection.puml
package java {
  
  package lang {
    interface Iterable<T>
    interface java.util.Collection extends Iterable
  }
  package util {
    interface Iterator<E>
    Iterator <.u. Iterable: creates
  }
  
}

@enduml
