@startuml
!include collection.puml
package java.util {
  
  interface Queue<E> extends Collection
  abstract AbstractQueue<E> extends AbstractCollection implements Queue
  interface Deque<E> extends Queue, SequencedCollection
  
}
@enduml
